import type { NextPage } from "next";
import Head from "next/head";
import { ChangeEvent, useEffect, useState } from "react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex h-screen flex-col items-center justify-center p-4">
        <UploadImages />
      </main>
    </>
  );
};

const UploadImages = () => {
  const [images, setImages] = useState<Array<File>>([]);
  const [imageURLS, setImageURLS] = useState<Array<string>>([]);

  useEffect(() => {
    setImageURLS(images.map((image) => URL.createObjectURL(image)));
  }, [images]);

  const onImageChange = (event: ChangeEvent<HTMLInputElement>) => {
    const { files } = event.target;
    if (files) {
      setImages(Array.from(files));
    }
  };

  return (
    <>
      <input
        type="file"
        accept="image/*"
        onChange={onImageChange}
        className="block text-sm text-slate-500 file:mr-4 file:rounded-full file:border-0 file:bg-violet-50 file:py-2 file:px-4 file:text-sm file:font-semibold file:text-violet-700 hover:file:bg-violet-100"
      />
      {imageURLS.map((imageURL, index) => (
        <div
          className="my-4 flex aspect-[9/16] h-5/6 flex-col place-content-center bg-slate-100"
          key={index}
        >
          <div
            contentEditable="true"
            className="aspect-[9/1.333333] text-center text-[4vh] font-bold leading-relaxed text-slate-500 outline-none"
          >
            Enter text here
          </div>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={imageURL}
            alt={`uploaded image`}
            className="aspect-[9/6] object-cover object-top"
          />
          <div
            contentEditable="true"
            className="aspect-[9/1.333333] text-center text-[4vh] font-bold leading-relaxed text-slate-500 outline-none"
          >
            Enter text here
          </div>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={imageURL}
            alt={`uploaded image`}
            className="aspect-[9/6] object-cover object-bottom"
          />
          <div
            contentEditable="true"
            className="aspect-[9/1.333333] text-center text-[4vh] font-bold leading-relaxed text-slate-500 outline-none"
          >
            Enter text here
          </div>
        </div>
      ))}
    </>
  );
};

export default Home;
